# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cppJSD <- function(p, q) {
    .Call('_speed_cppJSD', PACKAGE = 'speed', p, q)
}

#' @name distJSD
#' @title Jensen-Shannon divergence
#' 
#' @description Computes Jensen-Shannon divergence, which is based on Kullback-Leibler divergence. deq(\text{JSD}(A||B)=\frac{1}{2} \left( \text{KL}(A||M)+\text{KL}(B||M) \right))
#' 
#' @param inMatrix a positive-valued numeric matrix.
#' @export
distJSD <- function(inMatrix) {
    .Call('_speed_distJSD', PACKAGE = 'speed', inMatrix)
}

#' @name distJSD2
#' @title Jensen-Shannon divergence with two inputs
#' 
#' @description Computes Jensen-Shannon divergence, which is based on Kullback-Leibler divergence. deq(\text{JSD}(A||B)=\frac{1}{2} \left( \text{KL}(A||M)+\text{KL}(B||M) \right))
#' 
#' @param inMatrixTr a positive-valued numeric matrix of treated units.
#' @param inMatrixCo a positive-valued numeric matrix of controlled units.
#' @export
distJSD2 <- function(inMatrixTr, inMatrixCo) {
    .Call('_speed_distJSD2', PACKAGE = 'speed', inMatrixTr, inMatrixCo)
}

