# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_speed_wrappers", use_symbols = TRUE, package_name = "speed")

#' @usage NULL
#' @useDynLib speed, .registration = TRUE
NULL

#' Compute Jensen-Shannon divergence between two probability distributions.
#' @export
jsd_r <- function(p, q) .Call(wrap__jsd_r, p, q)

#' Compute Jensen-Shannon divergence matrix for a given input matrix.
#' @export
dist_jsd_r <- function(in_matrix) .Call(wrap__dist_jsd_r, in_matrix)

#' Compute Jensen-Shannon divergence matrix for two input matrices.
#' @export
dist_jsd2_r <- function(in_matrix_tr, in_matrix_co) .Call(wrap__dist_jsd2_r, in_matrix_tr, in_matrix_co)


# nolint end
