# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cppJSD <- function(x, y) {
    .Call('_speedmat_cppJSD', PACKAGE = 'speedmat', x, y)
}

#' @name distJSD
#' @title Jensen-Shannon divergence
#' 
#' @description Computes Jensen-Shannon divergence, which is based on Kullback-Leibler divergence. deq(\text{JSD}(A||B)=\frac{1}{2} \left( \text{KL}(A||M)+\text{KL}(B||M) \right))
#' 
#' @param inMatrix a positive-valued numeric matrix.
#' @export
distJSD <- function(inMatrix) {
    .Call('_speedmat_distJSD', PACKAGE = 'speedmat', inMatrix)
}

